name: Golang

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Format
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/master'
    permissions:
      packages: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"

    - name: Install tools
      uses: jdx/mise-action@v2

    - name: Set up Docker Buildx for cache
      uses: docker/setup-buildx-action@v3

    - name: Expose GitHub Runtime for cache
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Set up Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:deploy

    - name: Build, push and deploy
      run: kamal deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
